name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Build-and-Test:
    runs-on: windows
    steps:
      - name: Check out repository code
        uses: http://10.1.1.25:3000/Actions/checkout.git@v4
        with:
          submodules: 'recursive'
      - name: Init node_modules
        run: |
          cd client-node
          yarn
      - name: Configure CMake
        continue-on-error: false
        run: |
          mkdir -p build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A "Win32" -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=ON -DVCPKG_TARGET_TRIPLET=x86-windows-static  -DCMAKE_TOOLCHAIN_FILE=E:/Dev/vcpkg/scripts/buildsystems/vcpkg.cmake
          if ($LASTEXITCODE -ne 0) {
            Write-Error "CMake configuration failed with exit code $LASTEXITCODE"
            exit 1
          }
      - name: Build
        if: success()
        continue-on-error: false
        run: |
          cd build
          cmake --build . --target min_tests --config Release
          if ($LASTEXITCODE -ne 0) {
            Write-Error "CMake configuration failed with exit code $LASTEXITCODE"
            exit 1
          }
      - name: Run Tests
        if: success()
        continue-on-error: false
        run: |
          cd build\client\tests\
          ctest -C Release --output-on-failure -L min
          if ($LASTEXITCODE -ne 0) { 
            Write-Error "Tests failed with exit code $LASTEXITCODE"
            exit 1
          }