#add_compile_options(/W4)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /utf-8 /wd4996 /wd4100 /wd5054 /wd4020 /wd4018 /wd4200 /wd4459 /wd4389")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /MAP /OPT:REF /OPT:ICF /DEBUG:NONE")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /MAP /OPT:REF /OPT:ICF /DEBUG:NONE")
set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} /MAP /OPT:REF /OPT:ICF /DEBUG:NONE")
add_definitions("-D_WIN32_WINNT=0x0602")

#configure_file(
#    ${LEIGOD_IM_SDK_SRC_DIR}/platforms/version.rc.in
#    ${CMAKE_CURRENT_BINARY_DIR}/version.rc
#    @ONLY
#)
#
#set(LIMSDK_PLATFORM_RES
#    ${CMAKE_CURRENT_BINARY_DIR}/version.rc
#)